version: '3.0'

networks:

    it-mo:

services:

  backend:
    build:
      context: ./
      dockerfile: ./back/Dockerfile
    networks:
      - it-mo
    ports:
      - "8080:8080"
    depends_on:
      - database


  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    networks:
      - it-mo


  front:
    build:
      context: ./
      dockerfile: ./front/Dockerfile
    ports:
      - "80:80"
    networks:
      - it-mo
    depends_on:
      - backend
